### ISSUE TITLE
can't make under Linux Mint

### ISSUE THREAD

**Issue by jenenliu** [manateelazycat/mrkeyboard#4]
Check out the code, install dependencies, but when I cd into the directory, and type "make", there are some errors.

> valac -o main \
>     -X -w \
>     --pkg=clutter-1.0 \
>     --pkg=clutter-gtk-1.0 \
>     --pkg=clutter-x11-1.0 \
>     --pkg=gdk-x11-3.0 \
>     --pkg=gee-1.0 \
>     --pkg=gio-2.0 \
>     --pkg=gtk+-3.0 \
>     --pkg=json-glib-1.0 \
>     --pkg=xcb \
>     --pkg=x11-xcb \
>     --vapidir=./lib \
>     ./lib/draw.vala \
>     ./lib/keymap.vala \
>     ./lib/utils.vala \
>     application.vala \
>     image_button.vala \
>     tabbar.vala \
>     titlebar.vala \
>     window.vala \
>     window_manager.vala \
>     window_mode.vala \
>     window_rectangle.vala \
>     main.vala 
> error: Package `clutter-x11-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories
> Compilation failed: 1 error(s), 0 warning(s)
> make: **\* [main] Error 1

OS : Linux Mint 17.3

**Comment by manateelazycat** [comment]
Please try blew command to install dependences:

sudo apt-get install valac uuid-runtime mplayer2 libwebkitgtk-3.0-dev libgexiv2-dev libsqlite3-dev  gir1.2-gee-1.0 gir1.2-gtk-3.0 gir1.2-clutter-1.0 gir1.2-gtkclutter-1.0 gir1.2-poppler-0.18 gir1.2-vte-2.91 libgee-dev libgtk-3-dev libclutter-1.0-dev libclutter-gtk-1.0-dev libpoppler-glib-dev libvte-2.91-dev -y

Please let me know if you still failed to build.

**Comment by jenenliu** [comment]
> get valac uuid-runtime mplayer2 libwebkitgtk-3.0-dev libgexiv2-dev libsqlite3-dev gir1.2-gee-1.0 gir1.2-gtk-3.0 gir1.2-clutter-1.0 gir1.2-gtkclutter-1.0 gir1.2-poppler-0.18 gir1.2-vte-2.91 libgee-dev libgtk-3-dev libclutter-1.0-dev libclutter-gtk-1.0-dev libpoppler-glib-dev libvte-2.91-dev
> Reading package lists... Done
> Building dependency tree  
> Reading state information... Done
> E: Unable to locate package gir1.2-vte-2.91
> E: Couldn't find any package by regex 'gir1.2-vte-2.91'
> E: Unable to locate package libvte-2.91-dev
> E: Couldn't find any package by regex 'libvte-2.91-dev'

my OS is already up-to-date, but the newest version for gir1.2-vte and libvte is 2.9.0, I'll try to compile version 2.9.1.
thanks
